project:
  type: book
  output-dir: docs
book:
  title: "Ensamblaje y Anotación de Genomas Bacterianos"
  author: 
    - name: Héctor Fabio Espitia-Navarro
      affiliations:
        - name: Universidad de Nariño | Grupo de Investigación Salud Pública
          city: Pasto
          state: Nariño
          country: Colombia
        - name: 3M Company | Corporate Research Materials Lab
          city: Saint Paul
          state: MN
          country: EEUU
  date: today
  date-format: long
  margin-footer: 
    # ![](assets/images/udenar_logo_black.svg)
    margin_footer.qmd
  favicon:
    assets/images/book.svg
    # assets/images/favicon-16x16.png
    # assets/images/favicon.svg
  site-url: https://hspitia.github.io/bact-genome-assembly/
  sharing: [twitter, facebook, linkedin]
  sidebar:
    # logo: https://www.udenar.edu.co/recursos/wp-content/uploads/2021/09/logo-udenar-negro.png
    # footer: |
    #   Esto es un footer para el sidebar
    tools:
      - icon: github
        href: https://github.com/hspitia/bact-genome-assembly
  chapters:
    - index.qmd
    - setup.qmd
    - data.qmd
    - data_qual.qmd
    - assembly.qmd
    - assembly_qual.qmd
    # - annotation.qmd
    # - author.qmd
    - references.qmd
  appendices:
    - a-fastqc.qmd
  page-footer:
    left: |
      Ensamblaje y Anotación de Genomas Bacterianos, por <a href="https://www.linkedin.com/in/hespitianavarro/">Héctor Fabio Espitia-Navarro</a>
    center:
      - text: "Universidad de Nariño"
        href: "https://www.udenar.edu.co/"
      - text: "Grupo de Investigación Salud Pública"
        href: "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000008168"
    right: |
        Manual creado con <a href="https://quarto.org/">Quarto</a>

      # - text: "About"
      #   href: setup.qmd
      # - text: "License"
      #   href: data.qmd
      # - text: "Trademark"
      #   href: trademark.qmd
bibliography: 
  - references.bib
crossref:
  fig-title: Figura     # (default is "Figure")
  tbl-title: Tabla     # (default is "Table")
  title-delim: "."      # (default is ":")
execute:
  echo: true
  eval: true
  ouput: true
editor: visual
engine: knitr
knitr:
  opts_chunk: 
    engine.opts: '-l' # For Bash to include env variables
    # prompt: true
    # collapse: true
    # R.options:
    #   knitr.graphics.auto_pdf: true
environments: [wrapfigure] # From extension latex-environment
filters:
  - latex-environment
lang: es
language: 
  callout-tip-caption: "Consejo"
  title-block-author-single: "Autor"
format:
  html:
    fig-align: center
    # FONTS CONFIG
    # mainfont: "Diverda Sans Com"
    # mainfont: "IowanOldSt BT"
    # mainfont: "mathpazo"
    # mainfont: "Montserrat"
    # mainfont: "Palatino LT Std"
    # mainfont: "Palatino"
    # mainfont: "Source Sans Pro"
    # monofont: "Bitstream Vera Sans Mono"
    # monofont: "Fira Code"
    # monofont: "Fira Mono"
    # monofont: "Nanum Gothic Coding"
    # monofont: "Roboto Mono"
    # monofont: "Inconsolata"
    # monofont: "Monaco"
    # code-block-bg: "#e9ecef"
    # colorlinks: true
    # fontsize: 12pt
    theme: 
      light:
        # - cosmo
        - flatly
        - assets/css/custom_light.scss
      dark:
        # - cyborg
        - darkly
        - assets/css/custom_dark.scss
        # - slate
        # - superhero
  pdf:
    lang: es-ES
    pdf-engine: xelatex
    listings: true
    link-citations: true
    number-sections: true
    # For kranktz class
    # documentclass: latex/krantz
    # include-in-header: latex/preamble.tex
    # include-before-body: latex/before_body.tex
    # include-after-body: latex/after_body.tex
    # ## For koma-script class
    # documentclass: scrbook
    documentclass: scrreport
    include-in-header:
      latex/pre.tex
    keep-tex: true
    pagestyle: headings
    # LINK COLORS
    citecolor: BrickRed
    linkcolor: BrickRed
    urlcolor: BrickRed
    # FONTS CONFIG
    mainfont: "Iowan Old Style"
    # mainfont: "Palatino"
    # mainfont: "Source Sans Pro"
    # sansfont: "Diverda Sans Com"
    sansfont: "Montserrat"
    # sansfont: "Source Sans Pro"
    # monofont: "Bitstream Vera Sans Mono"
    monofont: "Fira Code"
    # monofont: "Fira Mono"
    # monofont: "Inconsolata"
    # monofont: "Monaco"
    # monofont: "JetBrains Mono"
    # monofont: "NanumGothicCoding"
    # monofont: "Roboto Mono"
    mainfontoptions:
      - Numbers=Proportional
    monofontoptions: 
      - Scale=0.8
      # - Scale=MatchLowercase
    

